name: fvm_app
description: Flutter Version Manager.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0-alpha.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  pubspec_parse: ^0.1.5
  github: ^7.0.3

  flutter_cache_manager: ^2.0.0
  flutter:
    sdk: flutter

  oktoast: ^2.3.2
  settings_ui: ^0.4.0
  material_floating_search_bar: ^0.2.3
  flutter_spinkit: ^4.1.2+1
  flutter_markdown: ^0.5.1
  material_design_icons_flutter: ^4.0.5755
  animations: ^1.1.2

  async: ^2.4.2
  pubspec_yaml: ^2.0.1
  url_launcher: ^5.7.10
  watcher: ^0.9.7+15
  google_fonts: ^1.1.1
  filesize: ^1.0.4
  hooks_riverpod: ^0.12.1
  date_time_format: ^1.0.0+4
  flutter_hooks: ^0.14.1
  path_provider: ^1.6.24
  file_chooser: ^0.1.6
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

  pub_api_client: ^1.0.9
  fvm: ^1.3.7

  hive: ^1.4.4
  hive_flutter: ^0.3.1

dev_dependencies:
  build_runner: ^1.10.6
  effective_dart: ^1.3.0
  flutter_test:
    sdk: flutter
  msix: ^0.1.15

flutter:
  uses-material-design: true
  assets:
    - assets/fvm-icon.png

msix_config:
  display_name: Sidekick
  publisher_display_name: Eduardo Moreno
  identity_name: dev.eduardom.sidekick
  msix_version: 0.3.0.0
  #  publisher: CN=Eduardo Moreno, O=Eduardo Moreno, L=Madrid, S=Madrid, C=ES
  logo_path: .\assets\fvm-icon.png
  start_menu_icon_path: .\assets\fvm-icon.png
  tile_icon_path: .\assets\fvm-icon.png
  icons_background_color: transparent
  architecture: x64
  capabilities: "internetClient,removableStorage"
