name: companion
title: Companion
version: 0.0.1
summary: Making Flutter Development Delighful.
description: A simple app to make Flutter development more delightful.

confinement: classic
base: core18
grade: stable

slots:
  dbus-companion: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: dev.eduardom.companion # adjust accordingly to your app name and

apps:
  companion:
    command: companion
    extensions: [flutter-dev] # Where "master" defines which Flutter channel to use for the build
    plugs:
      - network
    slots:
      - dbus-companion
parts:
  companion:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
