on:
  release:
    types: # This configuration does not affect the page_build event above
      - created

name: Release Artifacts

jobs:
  build-linux:
    name: "Build Linux"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v1.4.0

      - name: Install Linux build tools
        run: sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev libblkid-dev liblzma-dev

      - name: Enable desktop
        run: flutter config --enable-linux-desktop

      - name: Analyze Flutter
        run: flutter pub get

      - name: Flutter build app
        run: flutter build linux --build-name=${{ github.ref }}

      - name: Compress artifacts
        uses: TheDoctor0/zip-release@0.4.1
        with:
          path: ./build/linux/release/bundle
          filename: linux.zip

      - name: Upload files to a GitHub release
        # You may pin to the exact commit or the version.
        # uses: svenstaro/upload-release-action@483c1e56f95e88835747b1c7c60581215016cbf2
        uses: svenstaro/upload-release-action@2.2.1
        with:
          # GitHub token.
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          # Local file to upload.
          file: linux-${{ github.ref }}.zip
          # Tag to use as a release.
          tag: ${{ github.ref }}
  build-macos:
    name: "Build MacOS"
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v1.4.0

      - name: Set Up XCode
        uses: devbotsxyz/xcode-select@v1.1.0

      - name: Enable desktop
        run: flutter config --enable-macos-desktop

      - name: Analyze Flutter
        run: flutter pub get

      - name: Flutter build app
        run: flutter build macos --build-name=${{ github.ref }}

      - name: Compress artifacts
        run: zip -r macos.zip build/macos/Build/Products/Release/Companion.app

      - name: Upload files to a GitHub release
        # You may pin to the exact commit or the version.
        # uses: svenstaro/upload-release-action@483c1e56f95e88835747b1c7c60581215016cbf2
        uses: svenstaro/upload-release-action@2.2.1
        with:
          # GitHub token.
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          # Local file to upload.
          file: macos-${{ github.ref }}.zip
          # Tag to use as a release.
          tag: ${{ github.ref }}
  build-windows:
    name: "Build Windows"
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v1.4.0

      - name: Enable desktop
        run: flutter config --enable-windows-desktop

      - name: Analyze Flutter
        run: flutter pub get

      - name: Flutter build app
        run: flutter build windows --build-name=${{ github.ref }}

      - name: Compress artifacts
        run: tar.exe -a -c -f windows.zip build/windows/Runner/release

      - name: Upload files to a GitHub release
        # You may pin to the exact commit or the version.
        # uses: svenstaro/upload-release-action@483c1e56f95e88835747b1c7c60581215016cbf2
        uses: svenstaro/upload-release-action@2.2.1
        with:
          # GitHub token.
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          # Local file to upload.
          file: windows-${{ github.ref }}.zip
          # Tag to use as a release.
          tag: ${{ github.ref }}
