on:
  release:
    types: # This configuration does not affect the page_build event above
      - created

name: Lunix Release

jobs:
  build:
    name: "Build Linux"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2.3.4
      
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v1.4.0
        with:
          channel: stable
          
      - name: Enable desktop
        run: flutter config --enable-linux-desktop
        
      - name: Analyze Flutter
        run: flutter pub get
      
      - name: Flutter build app
        run: flutter build ${{ matrix.TARGET }}
        
      - name: Compress artifacts
        uses: TheDoctor0/zip-release@0.4.1
        with:
          path: ./build/linux
          filename: linux.zip
          
      - name: Upload files to a GitHub release
        # You may pin to the exact commit or the version.
        # uses: svenstaro/upload-release-action@483c1e56f95e88835747b1c7c60581215016cbf2
        uses: svenstaro/upload-release-action@2.2.1
        with:
          # GitHub token.
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          # Local file to upload.
          file: linux.zip
          # Tag to use as a release.
          tag: ${{ github.ref }}
