on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'App v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: "Build ${{ matrix.sdk-version }} / ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: packages/app
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        sdk-version: [dev] #, dev]
        include:
          - os: macOS-latest
            TARGET: macos
          - os: ubuntu-latest
            TARGET: linux
          - os: windows-latest
            TARGET: windows

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Setup Flutter ${{ matrix.sdk-version }}
        uses: DanTup/gh-actions/setup-flutter@master
        with:
          channel: ${{ matrix.sdk-version }}

      - name: Analyze Flutter
        run: flutter analyze
        
      - name: Enable desktop
        run: flutter config --enable-${{ matrix.TARGET }}-desktop
      
      - name: Flutter build app
        run: flutter build ${{ matrix.TARGET }}
        
      - name: Compress artifacts
        uses: TheDoctor0/zip-release@0.4.1
        with:
          path: ./build/${{ matrix.TARGET }}
          filename: ${{ matrix.TARGET }}.zip
          
      - name: Upload files to a GitHub release
        # You may pin to the exact commit or the version.
        # uses: svenstaro/upload-release-action@483c1e56f95e88835747b1c7c60581215016cbf2
        uses: svenstaro/upload-release-action@2.2.1
        with:
          # GitHub token.
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          # Local file to upload.
          file: ${{ matrix.TARGET }}.zip
          # Tag to use as a release.
          tag: ${{ github.ref }}
